package com.opensourcedev.ticketmanager.model.enums;

public enum ChangeType {

    INSTALLATION_OF_OS, SOFTWARE_INSTALLATION, CREDENTIALS_CHANGE, OS_SETTINGS_CHANGE,
    NETWORK_CONNECTION_PROPERTIES_CHANGE, MAJOR_UPDATE_OF_SOFTWARE
}
