package com.opensourcedev.ticketmanager.model.enums;

public enum IncidentType {

    ENVIRONMENT_NOT_AVAILABLE, PROXY_NOT_REACHABLE, SECURITY_ISSUE, NETWORK_CONNECTION_PROBLEM,
    EXPIRED_CREDENTIALS, UNSUCCESSFUL_BACKUP, DATABASE_CONNECTION_DOWN, PATCH_PROBLEM
}
