package com.opensourcedev.ticketmanager.model.users;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.opensourcedev.ticketmanager.model.items.ChangeTicket;
import com.opensourcedev.ticketmanager.model.items.Incident;
import com.opensourcedev.ticketmanager.model.items.Ticket;
import lombok.*;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Size;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
public class IncidentSolver {   // this user is responsible for solving all items, not only incidents

    @JsonIgnore
    @Id
    @GeneratedValue(generator="system-uuid")
    @GenericGenerator(name="system-uuid", strategy = "uuid")
    private String id;      // Secret ID generated by DB

    @NotBlank
    private String incidentId;

    @NotBlank
    @Size(min = 5, max = 50)
    @Column(unique = false, nullable = false)
    private String userName;

    @JsonIgnore
    @OneToOne(mappedBy = "incidentSolver")
    private ChangeTicket changeTicket;

    @JsonIgnore
    @OneToOne(mappedBy = "incidentSolver")
    private Incident incident;

    @JsonIgnore
    @OneToOne(mappedBy = "incidentSolver")
    private Ticket ticket;

}
