package com.opensourcedev.ticketmanager.model.users;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.opensourcedev.ticketmanager.model.enums.UserType;
import com.opensourcedev.ticketmanager.model.items.ChangeTicket;
import com.opensourcedev.ticketmanager.model.items.Incident;
import com.opensourcedev.ticketmanager.model.items.Ticket;
import lombok.*;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import javax.validation.constraints.*;


@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
public class User {     // This entity represents user who is reporting an item

    @JsonIgnore
    @Id
    @GeneratedValue(generator="system-uuid")
    @GenericGenerator(name="system-uuid", strategy = "uuid")
    private String id;      // Secret ID generated by DB

    @NotBlank
    private String userId;

    @Enumerated(value = EnumType.STRING)
    @NotNull
    private UserType userType;

    @NotBlank
    @Size(min = 5, max = 50)
    @Column(unique = false, nullable = false)
    private String userName;

    @JsonIgnore
    @OneToOne(mappedBy = "user")
    private ChangeTicket changeTicket;

    @JsonIgnore
    @OneToOne(mappedBy = "user")
    private Incident incident;

    @JsonIgnore
    @OneToOne(mappedBy = "user")
    private Ticket ticket;

}

