package com.opensourcedev.ticketmanager.model.items;

import com.opensourcedev.ticketmanager.model.enums.ItemStatus;
import com.opensourcedev.ticketmanager.model.users.IncidentSolver;
import com.opensourcedev.ticketmanager.model.users.User;
import lombok.*;

import java.sql.Timestamp;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class BaseItem {

    private String id;      // Secret ID generated by DB

    private ItemStatus itemStatus;

    private Timestamp createdAt;
    private Timestamp updatedAt;
    private Timestamp closedAt;

    private IncidentSolver incidentSolver;
    private User user;
}
